/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTestIndexRouteImport } from './routes/_app/test/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppTestIdRouteImport } from './routes/_app/test/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestIndexRoute = AppTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppTestIdRoute = AppTestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/test/$id': typeof AppTestIdRoute
  '/services/': typeof AppServicesIndexRoute
  '/test/': typeof AppTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/test/$id': typeof AppTestIdRoute
  '/services': typeof AppServicesIndexRoute
  '/test': typeof AppTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/test/$id': typeof AppTestIdRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/test/': typeof AppTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test/$id' | '/services/' | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test/$id' | '/services' | '/test'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/test/$id'
    | '/_app/services/'
    | '/_app/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test/': {
      id: '/_app/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof AppTestIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test/$id': {
      id: '/_app/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof AppTestIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTestIdRoute: typeof AppTestIdRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppTestIndexRoute: typeof AppTestIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTestIdRoute: AppTestIdRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppTestIndexRoute: AppTestIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
