/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppServicesIdRouteImport } from './routes/_app/services/$id'
import { Route as AppPaymentsIdRouteImport } from './routes/_app/payments/$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIdRoute = AppServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof PublicLoginRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/services/$id': typeof AppServicesIdRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/services/': typeof AppServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof PublicLoginRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/services/$id': typeof AppServicesIdRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/services': typeof AppServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/payments/$id': typeof AppPaymentsIdRoute
  '/_app/services/$id': typeof AppServicesIdRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/invoices/$id'
    | '/payments/$id'
    | '/services/$id'
    | '/invoices/'
    | '/payments/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/invoices/$id'
    | '/payments/$id'
    | '/services/$id'
    | '/invoices'
    | '/payments'
    | '/services'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_public/login'
    | '/_app/'
    | '/_app/invoices/$id'
    | '/_app/payments/$id'
    | '/_app/services/$id'
    | '/_app/invoices/'
    | '/_app/payments/'
    | '/_app/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$id': {
      id: '/_app/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AppServicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$id': {
      id: '/_app/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppServicesIdRoute: typeof AppServicesIdRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppServicesIdRoute: AppServicesIdRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
