[mcp_servers.better-t-stack]
args = [
    "dlx",
    "create-better-t-stack@latest",
    "mcp",
]
command = "pnpm"

[mcp_servers.context7]
args = [
    "-y",
    "@upstash/context7-mcp",
]
command = "npx"

[mcp_servers.heroui-react]
args = [
    "-y",
    "@heroui/react-mcp@latest",
]
command = "npx"

[mcp_servers.shadcn]
args = [
    "-y",
    "shadcn@latest",
    "mcp",
]
command = "npx"
