/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as EndpointsIndexRouteImport } from './routes/endpoints/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as AccountingIndexRouteImport } from './routes/accounting/index'
import { Route as ServicesIdRouteImport } from './routes/services/$id'
import { Route as ServersIdRouteImport } from './routes/servers/$id'
import { Route as PaymentsIdRouteImport } from './routes/payments/$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as EndpointsIdRouteImport } from './routes/endpoints/$id'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as AuditLogsIdRouteImport } from './routes/audit-logs/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsIndexRoute = EndpointsIndexRouteImport.update({
  id: '/endpoints/',
  path: '/endpoints/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingIndexRoute = AccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIdRoute = ServersIdRouteImport.update({
  id: '/servers/$id',
  path: '/servers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIdRoute = PaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsIdRoute = EndpointsIdRouteImport.update({
  id: '/endpoints/$id',
  path: '/endpoints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIdRoute = AuditLogsIdRouteImport.update({
  id: '/audit-logs/$id',
  path: '/audit-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/endpoints/$id': typeof EndpointsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/accounting/': typeof AccountingIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/endpoints/': typeof EndpointsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/endpoints/$id': typeof EndpointsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/accounting': typeof AccountingIndexRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/endpoints': typeof EndpointsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/servers': typeof ServersIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/endpoints/$id': typeof EndpointsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/payments/$id': typeof PaymentsIdRoute
  '/servers/$id': typeof ServersIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/accounting/': typeof AccountingIndexRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/endpoints/': typeof EndpointsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category'
    | '/login'
    | '/audit-logs/$id'
    | '/customers/$id'
    | '/endpoints/$id'
    | '/invoices/$id'
    | '/payments/$id'
    | '/servers/$id'
    | '/services/$id'
    | '/accounting/'
    | '/audit-logs/'
    | '/categories/'
    | '/customers/'
    | '/endpoints/'
    | '/invoices/'
    | '/payments/'
    | '/servers/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category'
    | '/login'
    | '/audit-logs/$id'
    | '/customers/$id'
    | '/endpoints/$id'
    | '/invoices/$id'
    | '/payments/$id'
    | '/servers/$id'
    | '/services/$id'
    | '/accounting'
    | '/audit-logs'
    | '/categories'
    | '/customers'
    | '/endpoints'
    | '/invoices'
    | '/payments'
    | '/servers'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/login'
    | '/audit-logs/$id'
    | '/customers/$id'
    | '/endpoints/$id'
    | '/invoices/$id'
    | '/payments/$id'
    | '/servers/$id'
    | '/services/$id'
    | '/accounting/'
    | '/audit-logs/'
    | '/categories/'
    | '/customers/'
    | '/endpoints/'
    | '/invoices/'
    | '/payments/'
    | '/servers/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  LoginRoute: typeof LoginRoute
  AuditLogsIdRoute: typeof AuditLogsIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  EndpointsIdRoute: typeof EndpointsIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  PaymentsIdRoute: typeof PaymentsIdRoute
  ServersIdRoute: typeof ServersIdRoute
  ServicesIdRoute: typeof ServicesIdRoute
  AccountingIndexRoute: typeof AccountingIndexRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  EndpointsIndexRoute: typeof EndpointsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/': {
      id: '/endpoints/'
      path: '/endpoints'
      fullPath: '/endpoints/'
      preLoaderRoute: typeof EndpointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/': {
      id: '/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AccountingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$id': {
      id: '/servers/$id'
      path: '/servers/$id'
      fullPath: '/servers/$id'
      preLoaderRoute: typeof ServersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$id': {
      id: '/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof PaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$id': {
      id: '/endpoints/$id'
      path: '/endpoints/$id'
      fullPath: '/endpoints/$id'
      preLoaderRoute: typeof EndpointsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/$id': {
      id: '/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/audit-logs/$id'
      preLoaderRoute: typeof AuditLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  LoginRoute: LoginRoute,
  AuditLogsIdRoute: AuditLogsIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  EndpointsIdRoute: EndpointsIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  PaymentsIdRoute: PaymentsIdRoute,
  ServersIdRoute: ServersIdRoute,
  ServicesIdRoute: ServicesIdRoute,
  AccountingIndexRoute: AccountingIndexRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  EndpointsIndexRoute: EndpointsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
