import { Injectable, Logger } from "@nestjs/common";
import { normalizePhoneNumber } from "../../../common/utils/phone.util";

export interface SendOtpResult {
  success: boolean;
  messageId?: number;
  cost?: number;
  errorMessage?: string;
}

const DEFAULT_KAVENEGAR_KEY =
  "46437751615871547A59364B75376339706E72384266734A596F3476644B653641356171462F557A5747383D";
const DEFAULT_KAVENEGAR_TEMPLATE = "gcotp";

@Injectable()
export class KavenegarService {
  private readonly logger = new Logger(KavenegarService.name);

  private getApiKey(): string {
    const key = process.env.KAVENEGAR_API_KEY?.trim();
    if (key && key !== "undefined" && key !== "null" && key.length > 10) {
      return key;
    }
    return DEFAULT_KAVENEGAR_KEY;
  }

  private getTemplate(): string {
    const template = process.env.KAVENEGAR_OTP_TEMPLATE?.trim();
    if (template && template !== "undefined" && template !== "null" && template.length > 0) {
      return template;
    }
    return DEFAULT_KAVENEGAR_TEMPLATE;
  }

  /**
   * Sends an OTP token via Kavenegar Verify Lookup API.
   * Pattern template: gcotp (or env KAVENEGAR_OTP_TEMPLATE)
   * receptor: normalized Iranian mobile number
   * token: OTP code generated by Auth logic
   */
  async sendOtp(
    phone: string,
    otp: string,
    template?: string,
  ): Promise<SendOtpResult> {
    const apiKey = this.getApiKey();
    const finalTemplate = template || this.getTemplate();
    const cleanPhone = normalizePhoneNumber(phone);

    if (!apiKey) {
      this.logger.warn(
        `KAVENEGAR_API_KEY is not configured. OTP for ${cleanPhone} will not be sent via SMS.`,
      );
      return { success: false, errorMessage: "کلید ارتباط با پنل پیامکی کاوه‌نگار تنظیم نشده است" };
    }

    if (!cleanPhone || !otp) {
      this.logger.error("Invalid phone or OTP provided to KavenegarService");
      return { success: false, errorMessage: "شماره موبایل یا کد تایید نامعتبر است" };
    }

    const endpoint = `https://api.kavenegar.com/v1/${apiKey}/verify/lookup.json`;

    try {
      const body = new URLSearchParams({
        receptor: cleanPhone,
        token: otp,
        template: finalTemplate,
      });

      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: body.toString(),
      });

      const responseData: any = await response.json().catch(() => null);

      if (!response.ok || responseData?.return?.status !== 200) {
        const statusCode = responseData?.return?.status || response.status;
        const statusMsg = responseData?.return?.message || response.statusText;
        const maskedPhone =
          cleanPhone.length >= 7
            ? `${cleanPhone.slice(0, 4)}***${cleanPhone.slice(-2)}`
            : cleanPhone;

        this.logger.error(
          `Kavenegar OTP dispatch failed for receptor ${maskedPhone}: [${statusCode}] ${statusMsg}`,
        );
        return { success: false, errorMessage: statusMsg || `خطای درگاه پیامک (${statusCode})` };
      }

      const entry = responseData?.entries?.[0];
      const maskedPhone =
        cleanPhone.length >= 7
          ? `${cleanPhone.slice(0, 4)}***${cleanPhone.slice(-2)}`
          : cleanPhone;

      this.logger.log(
        `Kavenegar OTP successfully dispatched to ${maskedPhone} (Template: ${finalTemplate}, MessageID: ${entry?.messageid || "N/A"})`,
      );

      return {
        success: true,
        messageId: entry?.messageid,
        cost: entry?.cost,
      };
    } catch (err: any) {
      const maskedPhone =
        cleanPhone.length >= 7
          ? `${cleanPhone.slice(0, 4)}***${cleanPhone.slice(-2)}`
          : cleanPhone;

      this.logger.error(
        `Exception occurred while sending OTP via Kavenegar to ${maskedPhone}: ${err.message}`,
        err.stack,
      );
      return { success: false, errorMessage: err.message || "خطا در برقراری ارتباط با کاوه‌نگار" };
    }
  }
}
